name: CI/CD

on: push

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo 
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Run tests 
        run: npm run test

  cd: 
    runs-on: ubuntu-latest 
    needs: ci 
    if: github.ref == 'refs/heads/main'  # Adjust the condition if needed
    steps: 
      - name: Checkout repo  
        uses: actions/checkout@v2

      - name: Install Railway 
        run: npm i -g @railway/cli

      - name: Debug Token
        run: |
          echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}"
          echo "Length: ${#RAILWAY_TOKEN}"

      - name: Deploy railway 
        run: railway up --service 456404c1-f880-4a7b-b0de-2331b2d2387d # add service id here 
        env: 
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
