name: CI/CD

on: push

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo 
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16 

      - name: Download deps
        run: npm i

      - name: Run tests 
        run: npm run test

  cd: 
    runs-on: ubuntu-latest 
    needs: ci 
    if: github.ref == 'refs/heads/main'  # Adjust the condition if needed
    steps: 
      - name: Checkout repo  
        uses: actions/checkout@v2

      - name: Install Railway 
        run: npm i -g @railway/cli

      - name: Debug Token
        run: |
          echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}"
          echo "Length: ${#RAILWAY_TOKEN}"

      - name: Deploy railway 
        run: railway up --service 4d49af01-32bb-4e77-ae97-28917f460ec8 # add service id here 
        env: 
          RAILWAY_TOKEN: 99533ffb-06f0-4100-b717-a9eb8d9869fd
