name: CI/CD

on: push

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo 
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Adjust c8 file permissions
        run: chmod +x node_modules/.bin/c8

      - name: Adjust ava file permissions
        run: chmod +x node_modules/.bin/ava
        
      - name: Run tests 
        run: npm run test

  cd: 
    runs-on: ubuntu-latest 
    needs: ci 
    if: github.ref == 'refs/heads/main'  # Adjust the condition if needed
    steps: 
      - name: Checkout repo  
        uses: actions/checkout@v2

      - name: Install Railway 
        run: npm i -g @railway/cli

      - name: Debug Token
        run: |
          echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}"
          echo "Length: ${#RAILWAY_TOKEN}"

      - name: Deploy railway 
        run: railway up --service 45c953ba-2d39-4c18-a110-a36e2aa094a8 # add service id here 
        env: 
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
